CREATE DATABASE CORCLIENTE  
ON (NAME = N'CORCLIENTE_Data', 
FILENAME = N'C:\Arquivos de programas\Microsoft SQL Server\MSSQL\data\CORCLIENTE_Data.MDF' , 
SIZE = 1, FILEGROWTH = 10%) 
LOG ON (NAME = N'CORCLIENTE_Log', 
FILENAME = N'C:\Arquivos de programas\Microsoft SQL Server\MSSQL\data\CORCLIENTE_Log.LDF' , 
SIZE = 1, FILEGROWTH = 5%)
COLLATE Latin1_General_CI_AS


USE CORCLIENTE

CREATE TABLE [TABUF] (
	[IDUF] [int] IDENTITY (1, 1) NOT NULL ,
	[NOME] [varchar] (150) COLLATE Latin1_General_CI_AS NULL ,
	 PRIMARY KEY  CLUSTERED 
	(
		[IDUF]
	)  ON [PRIMARY] 
) ON [PRIMARY]

GO
CREATE TABLE [TABCIDADE] (
	[IDCIDADE] [int] IDENTITY (1, 1) NOT NULL ,
	[NOME] [varchar] (250) COLLATE Latin1_General_CI_AS NOT NULL ,
	[IDUF] [int] NOT NULL ,
	 PRIMARY KEY  CLUSTERED 
	(
		[IDCIDADE]
	)  ON [PRIMARY] ,
	CONSTRAINT [FK_IDUF] FOREIGN KEY 
	(
		[IDUF]
	) REFERENCES [TABUF] (
		[IDUF]
	)
) ON [PRIMARY]
GO

CREATE TABLE TABCLICOR (
IDCORRETOR	INT,
IDCLIENTE  	INT) 

GO
CREATE TABLE [TABCLICOR] (
	[IDCORRETOR] [int] NOT NULL ,
	[IDCLIENTE] [int] NOT NULL ,
	CONSTRAINT [FK_TABCLICOR_IDCLIENTE] FOREIGN KEY 
	(
		[IDCLIENTE]
	) REFERENCES [TABCLIENTES] (
		[IDCLIENTE]
	),
	CONSTRAINT [FK_TABCLICOR_IDCORRETORES] FOREIGN KEY 
	(
		[IDCORRETOR]
	) REFERENCES [TABCORRETORES] (
		[IDCORRETOR]
	)
) ON [PRIMARY]
GO

CREATE TABLE [TABCLIENTES] (
	[IDCLIENTE] [int] IDENTITY (1, 1) NOT NULL ,
	[NOME] [varchar] (150) COLLATE Latin1_General_CI_AS NOT NULL ,
	[CPF] [varchar] (14) COLLATE Latin1_General_CI_AS NOT NULL ,
	[ENDERECO] [varchar] (250) COLLATE Latin1_General_CI_AS NOT NULL ,
	[IDUF] [int] NOT NULL ,
	[IDCIDADE] [int] NOT NULL ,
	[ATIVO] [bit] NULL ,
	 PRIMARY KEY  CLUSTERED 
	(
		[IDCLIENTE]
	)  ON [PRIMARY] ,
	CONSTRAINT [FK_TABCLIENTES_IDCIDADE] FOREIGN KEY 
	(
		[IDCIDADE]
	) REFERENCES [TABCIDADE] (
		[IDCIDADE]
	),
	CONSTRAINT [FK_TABCLIENTES_IDUF] FOREIGN KEY 
	(
		[IDUF]
	) REFERENCES [TABUF] (
		[IDUF]
	)
) ON [PRIMARY]
GO

CREATE TABLE [TABCORRETORES] (
	[IDCORRETOR] [int] IDENTITY (1, 1) NOT NULL ,
	[CODCORRETOR] [varchar] (50) COLLATE Latin1_General_CI_AS NULL ,
	[NOME] [varchar] (150) COLLATE Latin1_General_CI_AS NOT NULL ,
	[CPF] [varchar] (14) COLLATE Latin1_General_CI_AS NOT NULL ,
	 PRIMARY KEY  CLUSTERED 
	(
		[IDCORRETOR]
	)  ON [PRIMARY] 
) ON [PRIMARY]
GO



INSERT INTO TABUF (NOME) VALUES ('AC')
INSERT INTO TABUF (NOME) VALUES ('AL')
INSERT INTO TABUF (NOME) VALUES ('AM')
INSERT INTO TABUF (NOME) VALUES ('AP')
INSERT INTO TABUF (NOME) VALUES ('BA')
INSERT INTO TABUF (NOME) VALUES ('CE')
INSERT INTO TABUF (NOME) VALUES ('DF')
INSERT INTO TABUF (NOME) VALUES ('ES')
INSERT INTO TABUF (NOME) VALUES ('GO')
INSERT INTO TABUF (NOME) VALUES ('MA')
INSERT INTO TABUF (NOME) VALUES ('MG')
INSERT INTO TABUF (NOME) VALUES ('MS')
INSERT INTO TABUF (NOME) VALUES ('MT')
INSERT INTO TABUF (NOME) VALUES ('PA')
INSERT INTO TABUF (NOME) VALUES ('PB')
INSERT INTO TABUF (NOME) VALUES ('PE')
INSERT INTO TABUF (NOME) VALUES ('PI')
INSERT INTO TABUF (NOME) VALUES ('PR')
INSERT INTO TABUF (NOME) VALUES ('RJ')
INSERT INTO TABUF (NOME) VALUES ('RN')
INSERT INTO TABUF (NOME) VALUES ('RO')
INSERT INTO TABUF (NOME) VALUES ('RR')
INSERT INTO TABUF (NOME) VALUES ('RS')
INSERT INTO TABUF (NOME) VALUES ('SC')
INSERT INTO TABUF (NOME) VALUES ('SE')
INSERT INTO TABUF (NOME) VALUES ('SP')
INSERT INTO TABUF (NOME) VALUES ('TO')







